services:
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - S3_ENDPOINT_URL=http://s3:4566 #NOTE: I am not sure if here it should be http://s3:4566 OR http://localhost:4566
      - AWS_ACCESS_KEY_ID=FAKEFAKEFAKE
      - AWS_SECRET_ACCESS_KEY=FAKEFAKEFAKE
